config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get '/about', to:'pages#about'
  get '/contact', to:'pages#contact'

  resources :posts

  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: [:new, :create]
    resources :order_details, only: [:new, :create]
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :order_details
  monetize :price_cents

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  monetize :amount_cents
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :menu_item
  belongs_to :order
  monetize :sub_total_cents
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order, only: [ :new, :create ]

  def new
    authorize @order
  end

  def create
    authorize @order
    cookies = params[:details][:cookies_q].to_i
    brownies = params[:details][:brownies_q].to_i
    cakes = params[:details][:cakes_q].to_i
    if cookies > 0
      @order.order_details.create!(quantity: cookies, menu_item_id: 1,
                                   sub_total_cents: MenuItem.first.price_cents * cookies)
    end
    if brownies > 0
      @order.order_details.create!(quantity: brownies, menu_item_id: 2,
                                   sub_total_cents: MenuItem.second.price_cents * brownies)
    end
    if cakes > 0
      @order.order_details.create!(quantity: cakes, menu_item_id: 3,
                                   sub_total_cents: MenuItem.third.price_cents * cakes)
    end
    total = 0
    @order.order_details.each do |detail|
      total += detail.sub_total_cents.to_i
    end
    @order.update_attribute(:amount_cents, total)
    redirect_to new_order_payment_path(@order)

  end

private
  def order_details
    params.require(:details).permit(:cookies_q, :brownies_q, :cakes_q)
  end

  def set_order
    @order = Order.find(params[:order_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login

  def index
    @orders = policy_scope(Order).order(created_at: :desc)
  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
    authorize @order
  end

  def create
    @order = Order.create(user: current_user, state: 'pending')
    authorize @order
    redirect_to new_order_order_detail_path(@order)
  end

  private

    def require_login
      unless current_user
        redirect_to new_user_session_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @menu_items = MenuItem.all
  end

  def about
  end

  def contact
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
    authorize @order
  end

  def create
    authorize @order
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @order.amount_cents,
    description:  "Payment for order #{@order.id}",
    currency:     @order.amount.currency
  )

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to order_path(@order)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = policy_scope(Post).order(created_at: :desc)
  end


  def show
    authorize @post
  end

  def new
    @post = Post.new
    authorize @post
  end

  def edit
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    authorize @post
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar'  %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/order_details/create.html.erb
<h1>OrderDetails#create</h1>
<p>Find me in app/views/order_details/create.html.erb</p>

app/views/order_details/new.html.erb
<!-- <h2>Order# <%= @order.id %></h2> -->

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Order Placement</h1>
      <h3>How much do you want to Order?</h3>

      <%= form_for(:details,  url: order_order_details_path, html: {class: ""}) do |f| %>
        <div class="form-group">
          <%= f.label :cookies_q, "Cookies Quantity" %>
          <%= f.number_field(:cookies_q, in: 1..10, step: 1) %>
        </div>
        <div class="form-group">
          <%= f.label :brownies_q, "Brownies Quantity" %>
          <%= f.number_field(:brownies_q, in: 1..10, step: 1) %>
        </div>
        <div class="form-group">
          <%= f.label :cakes_q, "Cakes Quantity" %>
          <%= f.number_field(:cakes_q, in: 1..10, step: 1) %>
        </div>
        <%= f.submit "Place Order", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <h1>Orders:</h1>
    <% @orders.each do |order| %>
      <div class="order-description">
          <h4><strong>Order# <%= order.id %></strong></h4>
          <p>Status: <%= order.state %></p>
          <p>Placed on: <%= order.created_at.to_date %></p>
          <p>Contents:
            <% order.order_details.each do |detail| %>
            <p class="order-content"><%= detail.quantity %> <%= detail.menu_item.name %></p>
            <% end %>
          </p>
          <p>Total: <%= humanized_money_with_symbol(order.amount) %></p>
        <hr>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Order</h1>
      <ul>
        <li>Order ID: <%= @order.id %></li>
        <li>Status: <%= @order.state %></li>
        <li>Order Contents:
          <% @order.order_details.each do |detail| %>
            <p><%= detail.quantity %> <%= detail.menu_item.name %></p>
          <% end %>
        </li>
        <li>Total: <%= humanized_money_with_symbol(@order.amount) %></li>
      <ul>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1>Gluten Free Bakeshop Story</h1>
      <p>Baking runs in the family, and we all enjoy satisfying our sweet teeth with our bakes. However, one among our family turned-out to be gluten-insensitive. So to get him his fix, we tweaked our heirloom recipes to gluten-free munchies. It is now our goal to share them with the community. We hope you'll enjoy them as much as we do!</p>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Contact Us</h1>
      <h2>Address:</h2>
      <h4>#9 Katipunan, Quezon City, Philippines</h4>
      <h2>Telephone:</h2>
      <h4>(02)920-11-22</h4>
      <h2>Email:</h2>
      <h4>glutenfree@bakery.com</h4>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner"></div>
<div class="container">

  <h1 class='tag-line'>Your home for gluten-free goodies</h1>

</div>

<div class="container">
  <div class="row">
  <h2 class="menu">MENU</h2>
    <% @menu_items.each do |item| %>
      <div class="col-md-4 menu-cards">
        <%= image_tag item.photo_url %>
        <p class="menu-item"><strong><%= item.name %></strong></p>

        <div class="menu-text"><p><%= item.description %></p></div>
        <p class="menu-price"><%= humanized_money_with_symbol(item.price) %></p>

      </div>
    <% end %>

  </div>
  <div class="order">
    <%= form_tag orders_path do %>
    <%= submit_tag 'Place an Order', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Cart Contents</h1>
      <%= form_tag order_payments_path(@order) do %>
        <article>
          <label class="amount">
          <% @order.order_details.each do |detail| %>
            <p><%= detail.quantity %> <%= detail.menu_item.name %>: <%= humanized_money_with_symbol(detail.sub_total) %></p>
          <% end %>
            <span>Total Bill: <%= humanized_money_with_symbol(@order.amount) %></span>
          </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="Gluten Free Bakeshop"
          data-email="<%= current_user.email %>"
          data-description="Payment for <%= @order.id %>"
          data-amount="<%= @order.amount_cents %>"
          data-currency="<%= @order.amount.currency %>"></script>

      <% end %>

    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Editing Post</h1>

      <%= render 'form', post: @post %>

      <%= link_to 'Show', @post %> |
      <%= link_to 'Back', posts_path %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Posts</h1>
  <% @posts.each do |post| %>
    <div class="post">
      <h3><%= post.title %></h3>
      <span><%= post.created_at.to_date %></span>
      <p><%= post.content %></p>
      <% if policy(post).show? %>
        <td><%= link_to 'Show', post, class: "btn btn-info" %></td>
      <% end %>
      <% if policy(post).update? %>
        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-success"%></td>
      <% end %>
      <% if policy(post).destroy? %>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
      <% end %>
      <hr>
    </div>

  <% end %>
  <br>
  <% if policy(Post).new? %>
    <%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>
  <% end %>

  <hr>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Title:</strong>
        <%= @post.title %>
      </p>

      <p>
        <strong>Content:</strong>
        <%= @post.content %>
      </p>

      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Gluten Free Bakery", root_path, class: "logo" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "About", about_path, class: 'navbar-wagon-item navbar-wagon-link' %>
    <%= link_to 'Contact', contact_path, class: 'navbar-wagon-item navbar-wagon-link' %>
    <%= link_to 'Blog', posts_path, class: 'navbar-wagon-item navbar-wagon-link' %>
    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Orders", orders_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'navbar-wagon-item navbar-wagon-link' %>

    <% else %>
      <!-- Login link (when logged out) and Signup -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign-up", new_user_registration_path, class: 'navbar-wagon-item navbar-wagon-link' %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>